[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "base-uri 'self'; default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://gc.zgo.at; img-src 'self' https://paularmstrong.goatcounter.com/count; connect-src 'self' https://www.youtube-nocookie.com/oembed; frame-src 'self' https://www.youtube-nocookie.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"
